# Generated by Django 4.2.2 on 2023-07-06 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_useraddress_is_default'),
        ('carts', '0007_alter_order_to_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_shipments', to='authentication.useraddress'),
        ),
    ]
