# Generated by Django 4.2.2 on 2023-07-09 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0015_coupon'),
        ('carts', '0009_order_address_order_city_order_email_order_fname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admins.coupon'),
        ),
    ]
