# Generated by Django 4.2.2 on 2023-07-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0011_alter_order_payment_method_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
    ]
