# Generated by Django 4.2.2 on 2023-06-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_product_new_arrival'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='best_product',
            field=models.BooleanField(default=False),
        ),
    ]
