# Generated by Django 4.2.1 on 2023-06-23 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0008_cart_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='session_key',
        ),
    ]
