# Generated by Django 4.2.2 on 2023-06-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0011_alter_productimage_image1_alter_productimage_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
