# Generated by Django 4.2.2 on 2023-06-25 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0012_alter_product_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
