# Generated by Django 4.2.2 on 2023-07-02 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0013_remove_cartitem_cart_remove_cartitem_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter_Price',
            fields=[
                ('price', models.CharField(choices=[('10000 TO 30000', '10000 TO 30000'), ('30000 TO 40000', '30000 TO 40000'), ('40000 TO 60000', '40000 TO 60000'), ('60000 TO 100000', '60000 TO 100000'), ('100000 TO 150000', '100000 TO 150000')], max_length=60, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='filter_price',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.filter_price'),
        ),
    ]
