# Generated by Django 4.2.2 on 2023-07-26 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0015_coupon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
    ]
