# Generated by Django 4.2.1 on 2023-06-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_useraddress_email_useraddress_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
