# Generated by Django 4.2.2 on 2023-07-26 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_useraddress_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name should only contain alphabets and spaces.', regex='^[A-Za-z\\s]*$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
